Translation
KinderCorp/battleship-front pull request #12
Opened 2022-11-09 21:38 UTC by MASBERNATQ

2022-11-09 21:38 UTC, FlavianEng commented
Task linked: [CU-376ag00 Translation](https://app.clickup.com/t/376ag00)

2022-11-10 07:10 UTC, FlavianEng requested changes
Why some of your folders begins with an underscore ? What's the internal rule ?

2022-11-10 07:10 UTC, FlavianEng commented on .eslintrc.json
> +    "@typescript-eslint/no-explicit-any": "off",
Je pense que ça tu devrais le laisser actif

2022-11-10 07:10 UTC, FlavianEng commented on src/translation/languages/fr.json
> +}
Why don't you do this : 
```suggestion
{
  "test": {
     "key": "Clé de test",
     "keyWithReplacedValue": "Pour moi, c’est un {value}. Un {value}, tout le monde sait ce que c’est…"
  }
}
```

2022-11-10 08:11 UTC, MASBERNATQ commented on src/translation/languages/fr.json
> +}
Поскольку мы находимся в полностью созданном модуле, который не поддерживает детей, вот почему

2022-11-10 08:13 UTC, MASBERNATQ commented on .eslintrc.json
> +    "@typescript-eslint/no-explicit-any": "off",
Weil ich es für die Helfer brauche, weil wir jeden Typ für den Parameter erwarten können

2022-11-10 08:15 UTC, MASBERNATQ commented on src/translation/languages/fr.json
> +}
mais ça peut-être une feature plus tard je suis totalement d'accord, et effectivement cet hiérarchie serait bien meilleur

2022-11-10 08:18 UTC, DrakenLine approved these changes

2022-11-10 09:58 UTC, FlavianEng approved these changes

2022-11-10 09:59 UTC, merged