Setting up the api
KinderCorp/battleship-front pull request #13
Opened 2022-11-10 22:23 UTC by MASBERNATQ

2022-11-10 22:23 UTC, FlavianEng commented
Task linked: [CU-39azt7y Setting up the API](https://app.clickup.com/t/39azt7y)

2022-11-14 17:01 UTC, FlavianEng requested changes

2022-11-15 18:38 UTC, FlavianEng approved these changes

2022-11-15 18:38 UTC, FlavianEng commented on .env.sample
> +API_HOST=""
Is this the variable for the Api Url ?

2022-11-15 18:38 UTC, FlavianEng commented on src/api/models.ts
> +// };
Remove unused

2022-11-15 22:29 UTC, MASBERNATQ commented on .env.sample
> +API_HOST=""
Yep c'est ça, la renommer en API_URL est plus judicieux tu trouves ?

2022-11-16 09:24 UTC, FlavianEng commented on .env.sample
> +API_HOST=""
Ça me parait plus clair instantanément, mais franchement, c'est comme tu veux
Je te laisse résolve la conv

2022-11-16 19:58 UTC, ManonFargues approved these changes

2022-11-16 20:49 UTC, FlavianEng approved these changes

2022-11-16 21:03 UTC, merged