Component Modal
KinderCorp/battleship-front pull request #17
Opened 2022-11-20 12:29 UTC by MASBERNATQ

2022-11-20 12:29 UTC, FlavianEng commented
Task linked: [CU-38zmhyp Component Modal](https://app.clickup.com/t/38zmhyp)

2022-11-22 23:40 UTC, ManonFargues submitted a review, later dismissed

2022-11-23 08:24 UTC, DrakenLine approved these changes

2022-11-23 08:30 UTC, FlavianEng requested changes

2022-11-23 08:30 UTC, FlavianEng commented on src/shared/Header/components/Header.tsx
> +  rightSideNode = null,
What's the nodes ? Is that possible to add JSDoc ?

2022-11-23 08:30 UTC, FlavianEng commented on src/shared/Modal/components/Modal.tsx
> +  // TODO: rightSide modal
Has this comment been forgotten ?

2022-11-23 14:59 UTC, MASBERNATQ commented on src/shared/Modal/components/Modal.tsx
> +  // TODO: rightSide modal
✅

2022-11-23 15:01 UTC, MASBERNATQ commented on src/shared/Header/components/Header.tsx
> +  rightSideNode = null,
C'est un suffix qui je pense peut-être pas mal, une sorte de nomenclature qui dirait que la props contient qqch de type `ReactNode`. En gros children c'est un node

2022-11-23 17:06 UTC, FlavianEng approved these changes

2022-11-24 08:20 UTC, DrakenLine approved these changes

2022-11-24 08:25 UTC, merged