Component Item
KinderCorp/battleship-front pull request #30
Opened 2022-12-05 21:19 UTC by DrakenLine

2022-12-05 21:19 UTC, FlavianEng commented
Task linked: [CU-38zmkr8 Component Item](https://app.clickup.com/t/38zmkr8)

2022-12-06 13:58 UTC, MASBERNATQ commented on styles/index.scss
> +@import '~@shared/Item/styles/Item';
Tu peux trier par ordre alphabétique

2022-12-06 13:58 UTC, MASBERNATQ commented on src/shared/Item/models.ts
> +  isLocked: boolean; //pas débloqué par le joueur
il faut que ça soit optionnel `isLocked?: boolean;`

2022-12-06 13:58 UTC, MASBERNATQ commented on src/shared/Item/models.ts
> +  numberOfUses : number | string, // - 1 sera égal à infini
il faut que ça soit optionnel `numberOfUses?: number;` (tu peux enlever le string)

2022-12-06 13:58 UTC, MASBERNATQ commented on src/shared/Item/models.ts
> +  isSelected: boolean, //choisi pour tirer
il faut que ça soit optionnel `isSelected?: boolean;`

2022-12-06 13:58 UTC, MASBERNATQ commented on src/shared/Item/models.ts
> +import type { ImageProps } from "@shared/Image/models";
Les commentaires peuvent être retiré sauf le cas particulié pour `numberOfUses` sur lequel tu peux indiquer `// if -1 then unlimited number of uses` (en anglais quoi)

2022-12-06 13:58 UTC, MASBERNATQ commented on src/shared/Item/components/Item.tsx
> +    )
à supprimer tu gèreras le styles enfant en passant par son parent `.item`

2022-12-06 13:58 UTC, MASBERNATQ commented on src/shared/Item/components/Item.tsx
> +            <Image src={src} alt={''} className={imgClassName}/>
- ici tu peux utiliser la props **name** (cf `model.ts`) afin de remplir le _alt_
- tu peux enlever la className

2022-12-06 23:47 UTC, FlavianEng requested changes

2022-12-06 23:47 UTC, FlavianEng commented on src/shared/Item/models.ts
> +  isDisabled : boolean, //pas choisi dans les paramètres ou plus de tirs dispo
Peut-on mettre les commentaires en anglais pls ?

2022-12-07 07:23 UTC, DrakenLine commented on src/shared/Item/models.ts
> +  isDisabled : boolean, //pas choisi dans les paramètres ou plus de tirs dispo
la plus part vont être enlevés (c'était un mémo pour pas me perdre) mais ceux restant ont été traduit :)

2022-12-07 20:46 UTC, MASBERNATQ commented on src/shared/Item/models.ts
> +  isDisabled : boolean, //pas choisi dans les paramètres ou plus de tirs dispo
your comment is english pls!

2022-12-09 08:43 UTC, FlavianEng submitted a review, later dismissed

2022-12-09 08:46 UTC, ManonFargues submitted a review, later dismissed

2022-12-30 16:27 UTC, FlavianEng commented on src/boat/helpers.ts
> +): direction is BoatDirection.WEST | BoatDirection.EAST => {
Why changing this type ? Boolean wasn't good enough ?

2022-12-30 16:32 UTC, FlavianEng approved these changes

2022-12-30 16:34 UTC, MaximeWrlz approved these changes

2022-12-30 16:39 UTC, merged