Create page for boats placement
KinderCorp/battleship-front pull request #32
Opened 2022-12-08 22:09 UTC by MASBERNATQ

2022-12-08 22:09 UTC, FlavianEng commented
Task linked: [CU-3d37uch Create page Boat placement](https://app.clickup.com/t/3d37uch)

2022-12-09 08:06 UTC, ManonFargues approved these changes

2022-12-09 08:22 UTC, DrakenLine approved these changes

2022-12-26 07:34 UTC, FlavianEng commented on README.md
> -- [Baptiste BONNIN](https://github.com/exender)
oui

2022-12-26 08:12 UTC, FlavianEng requested changes

2022-12-26 08:12 UTC, FlavianEng commented on src/boat/helpers.ts
> +    }
According to clean code principles, don't use else if and replace them with early return statement.

Can you rework this early return statement pls ?

2022-12-26 08:12 UTC, FlavianEng commented on src/boat/helpers.ts
> +  direction: boardBoat.direction || 'north',
```suggestion
  direction: boardBoat.direction || BoatDirection.NORTH,
```

2022-12-26 08:12 UTC, FlavianEng commented on src/boat/helpers.ts
> +  // FIXME: default direction in constants file
Can you do it now please ? I mean it only takes a few minutes

2022-12-26 08:12 UTC, FlavianEng commented on src/boat/models.ts
> +export type BoatDirection = 'east' | 'north' | 'south' | 'west';
Transform to enum ! 
Then if you want to get a TypeScript from an enum, write this : `` `${BoatDirection}` ``

2022-12-26 08:12 UTC, FlavianEng commented on src/boat/models.ts
> +  height: number; // For the length
We'll find something that is more appropriate

2022-12-26 08:12 UTC, FlavianEng commented on src/core/models.ts
> +export type IntRange<F extends number, T extends number> = Exclude<Enumerate<T>, Enumerate<F>> | T;
Can you explain me this modification please ?

2022-12-26 08:12 UTC, FlavianEng commented on src/game/components/GameOneVersusOne/GamePageView.tsx
> +      {view === 'boats_placement' && <GamePlacingBoatsView />}
Maybe it could be interesting to use a ViewEnum

2022-12-26 09:03 UTC, FlavianEng commented on src/game/components/GameOneVersusOne/GamePlacingBoatsView.tsx
> +  );
This only works for one versus one mode, maybe you could rewrite this to handle more than 2 players ? (Optional)

2022-12-26 09:41 UTC, FlavianEng commented on src/game/components/GameOneVersusOne/GamePlacingBoatsView.tsx
> +          plural: counterTime > 1 ? 's' : '',
Is this working ?
```suggestion
          plural: counterTime > 1 && 's' ,
```

2022-12-26 09:41 UTC, FlavianEng commented on src/game/components/GameOneVersusOne/GamePlacingBoatsView.tsx
> +    }
According to clean code principles, don't use else if and replace them with early return statement.

Can you rewrite this code part please ?

2022-12-26 09:41 UTC, FlavianEng commented on src/game/components/GameOneVersusOne/GameSettingsView.tsx
> +  const gameRoom = useSelector(selectGameRoom) as GameRoom;
Why do you need to cast this type ?

2022-12-26 09:41 UTC, FlavianEng commented on src/game/helpers.ts
> +  gameRoom: parseGameRoom(gameState.gameRoom),
Can you type this any please ?

2022-12-26 09:41 UTC, FlavianEng commented on src/game/helpers.ts
> +export const parseGameRoomData = (gameRoomData: any): GameRoomData<any> => ({
Can you type this any please ?

2022-12-26 09:41 UTC, FlavianEng commented on src/game/helpers.ts
> +export const parseGamePlayer = (gamePlayer: any): GamePlayer => ({
Can you type this any pls ?

2022-12-26 09:41 UTC, FlavianEng commented on src/game/helpers.ts
> +export const parseGamePlayers = (gamePlayers: any): GamePlayer[] =>
Can you type this any pls ?

2022-12-26 09:41 UTC, FlavianEng commented on src/game/helpers.ts
> +    : [];
This function is always the same but with a different map / array. Maybe you could refactor theses functions to create a generic function

_(Optional for now)_

2022-12-26 09:41 UTC, FlavianEng commented on src/game/helpers.ts
> +export const parseGameSettings = (gameSettings: any): GameSettings => ({
Can you type theses any please ?

2022-12-26 09:41 UTC, FlavianEng commented on src/game/helpers.ts
> +  hasBoatsSafetyZone: gameSettings?.hasBoatsSafetyZone || GAME_SETTINGS.hasBoatsSafetyZone,
This is not working, if there is an intentionally gameSettings.hasBoatsSafetyZone set to false, the default value we'll be taken

2022-12-26 09:41 UTC, FlavianEng commented on src/game/helpers.ts
> +export const parseGameRoomSettings = (gameRoomSettings: any): GameRoomSettings => ({
Can you type theses any type pls ?

2022-12-26 09:41 UTC, FlavianEng commented on src/game/helpers.ts
> +export const parseGameRoom = (gameRoom: any): GameRoom => ({
Can you type this any pls ?

2022-12-26 09:41 UTC, FlavianEng commented on src/game/helpers.ts
> +export const parsePosition = (position: any): Position => ({
Can you type this any please ?

2022-12-26 09:41 UTC, FlavianEng commented on src/game/helpers.ts
> +export const parsePositions = (positions: any): Position[] =>
Can you type this any please ?

2022-12-26 09:41 UTC, FlavianEng commented on src/game/models.ts
>  export type GameView = 'boats_placement' | 'playing' | 'settings';
Transform to enum !
Then if you want to get a TypeScript from an enum, write this : `${GameView}`

2022-12-26 09:41 UTC, FlavianEng commented on src/game/models.ts
>    weapons: Weapon['name'][];
Maybe this property could be name weaponNames in order to fit the type ?
```suggestion
  weaponNames: Weapon['name'][];
```

2022-12-26 09:41 UTC, FlavianEng commented on src/game/models.ts
> +  weapons: Weapon[];
Maybe this property could be name weaponNames in order to fit the type ?

```suggestion
  weaponNames: Weapon[];
```

2022-12-26 09:41 UTC, FlavianEng commented on src/game/models.ts
> +// FIXME: rename this
Info : In the backend, it's named `RoomData`

2022-12-26 09:41 UTC, FlavianEng commented on src/game/selectors.ts
> +  (state: GamePlayer[]): GamePlayer => state.find((player) => player.isHost) || ({} as GamePlayer),
The default case `({} as GamePlayer)` should never happen, right ?

2022-12-26 09:41 UTC, FlavianEng commented on src/game/selectors.ts
> +  (state: GamePlayer[]): GamePlayer => state.find((player) => player.isHost) || ({} as GamePlayer),
Same question for below code

2022-12-26 09:41 UTC, FlavianEng commented on src/home/components/HomePageContent.tsx
> +    dispatch(setGameRoom({} as GameRoom));
Why do you need to cast the type ?

2022-12-26 09:41 UTC, FlavianEng commented on src/player/models.ts
> +export type PlayersCardsSize = 'medium' | 'small';
Transform to enum !
Then if you want to get a TypeScript from an enum, write this : ${PlayersCardsSize}

This way, you avoid using hard-coded values in your code

2022-12-26 09:41 UTC, FlavianEng commented on src/shared/BlockContainer/components/BlockContainer.tsx
> +        // FIXME: bad code
Why don't you fix it now ?

2022-12-26 09:41 UTC, FlavianEng commented on src/shared/Board/components/Board.tsx
> +      }
According to clean code principles, don't use else if and replace them with early return statement.

Can you rewrite it pls ?

2022-12-26 09:41 UTC, FlavianEng commented on src/shared/Board/helpers.ts
> +  const takenCells = [] as Position[];
```suggestion
  const takenCells: Position[] = [];
```

2022-12-26 09:41 UTC, FlavianEng commented on src/shared/Icon/constants.ts
> +  Trophy: dynamic(() => import('@shared/Icon/components/IconTrophy'), { suspense: false }),
In this case, maybe you could create a const `DEFAULT_SUSPENSE_STATE` ?

2022-12-26 09:41 UTC, FlavianEng commented on src/shared/Level/models.ts
> +export type LevelRank = IntRange<1, 10>;
Are you sure, I think the last item is not included

2022-12-26 09:41 UTC, FlavianEng commented on src/shared/Title/models.ts
>  export type TitleType = 'h1' | 'h2' | 'h3' | 'h4' | 'none';
You could also create an enum here

2022-12-26 09:41 UTC, FlavianEng commented on src/shared/UserCard/models.ts
>    onClick?: (event: SyntheticEvent<EventTarget>) => void;
Why don't you do it ?

2022-12-26 09:41 UTC, FlavianEng commented on src/shared/_helpers/ArrayHelpers.ts
> +  }
Not sure it works

2022-12-26 09:41 UTC, FlavianEng commented on src/shared/_helpers/ArrayHelpers.ts
> +
Can you fix the any types ? 
Here, something that should work 

```suggestion
   * @param {unknown} value Value to check
   * @return {boolean}
   */
  static isArray(value: unknown): boolean {
    return Array.isArray(value);
  }

```

2022-12-26 09:41 UTC, FlavianEng commented on src/shared/_helpers/ArrayHelpers.ts
> +  static isEmpty(value: any): any {
Can you fix the any types please ?

```suggestion
   * @param {unknown} value Value to check
   * @return {boolean}
   */
  static isEmpty(value: unknown): boolean {
```

2022-12-26 09:41 UTC, FlavianEng commented on src/socket/listeningEvents.ts
> +// FIXME: assign the right type for parameter or just 'any' ?
The right type

2022-12-26 09:41 UTC, FlavianEng commented on src/socket/listeningEvents.ts
> +// FIXME: assign the right type for parameter or just 'any' ?
Using any is like coding in JavaScript

2022-12-26 09:41 UTC, FlavianEng commented on src/socket/listeningEvents.ts
> +export const listeningPlayerJoined = (gameRoomData: any): void => {
Can you fix this any type pls

2022-12-26 09:41 UTC, FlavianEng commented on src/socket/listeningEvents.ts
> +export const listeningGameCreated = (gameRoomData: any): void => {
Can you fix this any type ?

2022-12-26 09:41 UTC, FlavianEng commented on src/socket/listeningEvents.ts
> +export const listeningGameInformation = (gameRoomData: any): void => {
Can you fix this any type ?

2022-12-26 09:41 UTC, FlavianEng commented on src/socket/listeningEvents.ts
> +export const listeningOnePlayerHasPlacedHisBoats = (gameRoomData: any): void => {
Can you fix this any type ?

2022-12-26 09:41 UTC, FlavianEng commented on src/weapon/helpers.ts
> +export const parseWeapon = (weapon: any): Weapon => ({
Can you fix this any type ?

2022-12-26 09:41 UTC, FlavianEng commented on src/weapon/helpers.ts
> +  maxAmmunition: weapon?.maxAmmunition || 0,
Isn't the default value -1 ?

2022-12-26 09:41 UTC, FlavianEng commented on src/weapon/helpers.ts
> +  ArrayHelpers.isArray(weapons) ? weapons.map((weapon: any) => parseWeapon(weapon)) : [];
Can you fix this any type ?

2022-12-26 12:29 UTC, MASBERNATQ commented on README.md
> -- [Baptiste BONNIN](https://github.com/exender)
👍

2022-12-26 12:33 UTC, MASBERNATQ commented on pages/game/[gameId].tsx
>  import { useSelector } from 'react-redux';
non bien vu c'est un mauvais tri de ma part, ils sont censé être séparé

2022-12-26 12:33 UTC, MASBERNATQ commented on pages/game/[gameId].tsx
>  import { useSelector } from 'react-redux';
✅

2022-12-26 12:51 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +  ]);
Pour faire ça il faudra que je passe en enum chose que je n'ai pas faite pour le moment. Le passage en enum sera géré dans un ticket de refacto (ticket mère : https://app.clickup.com/t/3ba0eee)

2022-12-26 12:53 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +  // FIXME: check is it possible to place all boats, otherwise infinite loop
✅

2022-12-26 12:56 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +  else return 'north';
✅ (les textes en dur seront remplacés par des enums lors de la refacto)

2022-12-26 13:10 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +  ]);
✅

2022-12-26 13:11 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +  else return 'north';
✅

2022-12-26 13:11 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +  return direction === 'west' || direction === 'east';
✅

2022-12-26 13:11 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +  return direction === 'east' || direction === 'south';
✅

2022-12-26 13:47 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +export const hasXAxisReversed = (direction?: BoatDirection): boolean => {
✅

2022-12-26 13:48 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +export const isBoatHorizontal = (direction?: BoatDirection): boolean => {
✅

2022-12-26 13:48 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +export const hasYAxisReversed = (direction?: BoatDirection): boolean => {
✅

2022-12-26 13:55 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +  return direction === 'west' || direction === 'south';
✅

2022-12-26 13:55 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +// FIXME: rename length/width API properties to lengthCell/widthCell
✅

2022-12-26 13:57 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +export const parseBoat = (boat: any): Boat => ({
On ne peut pas savoir ce que l'api nous renverra malheureusement

2022-12-26 13:57 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +export const parseBoats = (boats: any): Boat[] =>
On ne peut pas savoir ce que l'api nous renverra malheureusement

2022-12-26 13:58 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +  ArrayHelpers.isArray(boats) ? boats.map((boat: any) => parseBoat(boat)) : [];
On ne peut pas savoir ce que l'api nous renverra malheureusement

2022-12-26 13:58 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +export const parseAuthorizedBoat = (authorizedBoat: any): AuthorizedBoat => ({
On ne peut pas savoir ce que l'api nous renverra malheureusement

2022-12-26 13:59 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +  // FIXME: change this bad parsed
Parce que je ne vois pas comment faire pour le moment, je compte en parler à mon taff, mais si tu as une idée je suis preneur

2022-12-26 13:59 UTC, MASBERNATQ commented on src/boat/helpers.ts
> + * @param {any} authorisedFleet Authorized fleet
On ne peut pas savoir ce que l'api nous renverra malheureusement

2022-12-26 14:00 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +  const boats = [] as Boat[];
✅

2022-12-26 14:01 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +  const bowCells = [] as ApiPosition[];
✅

2022-12-26 14:03 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +    }
c'est-à-dire ?

2022-12-26 14:03 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +  direction: boardBoat.direction || 'north',
✅

2022-12-26 14:03 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +  // FIXME: default direction in constants file
✅

2022-12-26 14:04 UTC, MASBERNATQ commented on src/boat/models.ts
> +export type BoatDirection = 'east' | 'north' | 'south' | 'west';
✅

2022-12-26 14:04 UTC, MASBERNATQ commented on src/boat/models.ts
> +  height: number; // For the length
👍

2022-12-26 14:06 UTC, MASBERNATQ commented on src/core/models.ts
> +export type IntRange<F extends number, T extends number> = Exclude<Enumerate<T>, Enumerate<F>> | T;
Pour prendre l'intervalle en entier. En l'occurrence avant cette modification si l'on voulait de 1 à 10 (compris) il fallait faire `IntRange<1, 11>`. Maintenant on peut faire `IntRange<1, 10>`

2022-12-26 14:06 UTC, MASBERNATQ commented on src/core/models.ts
> +export type IntRange<F extends number, T extends number> = Exclude<Enumerate<T>, Enumerate<F>> | T;
✅

2022-12-26 14:10 UTC, MASBERNATQ commented on src/game/components/GameOneVersusOne/GamePageView.tsx
> +      {view === 'boats_placement' && <GamePlacingBoatsView />}
✅

2022-12-26 14:15 UTC, MASBERNATQ commented on src/game/components/GameOneVersusOne/GamePlacingBoatsView.tsx
> +          plural: counterTime > 1 ? 's' : '',
Si `counterTime <= 1` l'opération nous renvoie `false`, on doit passer par un opérateur `? :` pour contourner ce problème

2022-12-26 14:15 UTC, MASBERNATQ commented on src/game/components/GameOneVersusOne/GamePlacingBoatsView.tsx
> +          plural: counterTime > 1 ? 's' : '',
✅

2022-12-26 14:16 UTC, MASBERNATQ commented on src/game/components/GameOneVersusOne/GamePlacingBoatsView.tsx
> +    }
c'est-à-dire ?

2022-12-26 14:17 UTC, MASBERNATQ commented on src/game/helpers.ts
> +  gameRoom: parseGameRoom(gameState.gameRoom),
✅

2022-12-26 14:18 UTC, MASBERNATQ commented on src/game/helpers.ts
> +export const parseGameRoomData = (gameRoomData: any): GameRoomData<any> => ({
On ne peut pas savoir ce que l'api nous renverra malheureusement

2022-12-26 14:18 UTC, MASBERNATQ commented on src/game/helpers.ts
> +export const parseGamePlayer = (gamePlayer: any): GamePlayer => ({
On ne peut pas savoir ce que l'api nous renverra malheureusement

2022-12-26 14:18 UTC, MASBERNATQ commented on src/game/helpers.ts
> +export const parseGamePlayers = (gamePlayers: any): GamePlayer[] =>
On ne peut pas savoir ce que l'api nous renverra malheureusement

2022-12-26 14:19 UTC, MASBERNATQ commented on src/game/helpers.ts
> +export const parseGameSettings = (gameSettings: any): GameSettings => ({
On ne peut pas savoir ce que l'api nous renverra malheureusement

2022-12-26 14:20 UTC, MASBERNATQ commented on src/game/helpers.ts
> +  hasBoatsSafetyZone: gameSettings?.hasBoatsSafetyZone || GAME_SETTINGS.hasBoatsSafetyZone,
✅

2022-12-26 14:22 UTC, MASBERNATQ commented on src/game/components/GameOneVersusOne/GamePlacingBoatsView.tsx
> +  );
Pas gênant car on se trouve dans le domaine `Game>GameOneVersusOne` (à voir dans le ticket de refacto)

2022-12-26 14:22 UTC, MASBERNATQ commented on src/game/helpers.ts
> +export const parseGameRoomSettings = (gameRoomSettings: any): GameRoomSettings => ({
On ne peut pas savoir ce que l'api nous renverra malheureusement

2022-12-26 14:22 UTC, MASBERNATQ commented on src/game/helpers.ts
> +export const parseGameRoom = (gameRoom: any): GameRoom => ({
On ne peut pas savoir ce que l'api nous renverra malheureusement

2022-12-26 14:22 UTC, MASBERNATQ commented on src/game/helpers.ts
> +export const parsePosition = (position: any): Position => ({
On ne peut pas savoir ce que l'api nous renverra malheureusement

2022-12-26 14:23 UTC, MASBERNATQ commented on src/game/helpers.ts
> +export const parsePositions = (positions: any): Position[] =>
On ne peut pas savoir ce que l'api nous renverra malheureusement

2022-12-26 14:24 UTC, MASBERNATQ commented on src/game/models.ts
>  export type GameView = 'boats_placement' | 'playing' | 'settings';
✅

2022-12-26 14:26 UTC, MASBERNATQ commented on src/game/models.ts
>    weapons: Weapon['name'][];
✅

2022-12-26 14:27 UTC, MASBERNATQ commented on src/game/models.ts
> +  weapons: Weapon[];
Je vais laisser `weapons` pour le moment puis quand le call API pour récupérer les armes sera fait ici je pourrais mettre `weaponNames`

2022-12-26 14:32 UTC, MASBERNATQ commented on src/game/models.ts
> +// FIXME: rename this
✅

2022-12-26 14:34 UTC, MASBERNATQ commented on src/game/selectors.ts
> +  (state: GamePlayer[]): GamePlayer => state.find((player) => player.isHost) || ({} as GamePlayer),
Ce cas arrive si l'API a renvoyé une mauvaise donnée ou qu'un problème interne est survenu sur l'hydratation du store

2022-12-26 14:38 UTC, MASBERNATQ commented on src/home/components/HomePageContent.tsx
> +    dispatch(setGameRoom({} as GameRoom));
Je suis obligé (sauf s'il y a une meilleure façon de faire) car `{}` n'est pas de type **GameRoom**

2022-12-26 14:39 UTC, MASBERNATQ commented on src/shared/BlockContainer/components/BlockContainer.tsx
> +        // FIXME: bad code
Car je ne sais pas comment l'améliorer, si tu sais je suis preneur !

2022-12-26 14:42 UTC, MASBERNATQ commented on src/player/models.ts
> +export type PlayersCardsSize = 'medium' | 'small';
Je ferais cette conversion lors de la refacto

2022-12-26 14:42 UTC, MASBERNATQ commented on src/shared/Board/components/Board.tsx
> +      }
c'est-à-dire ?

2022-12-26 14:42 UTC, MASBERNATQ commented on src/shared/Board/helpers.ts
> +  const takenCells = [] as Position[];
✅

2022-12-26 14:45 UTC, MASBERNATQ commented on src/shared/Icon/constants.ts
> +  Trophy: dynamic(() => import('@shared/Icon/components/IconTrophy'), { suspense: false }),
✅

2022-12-26 14:46 UTC, MASBERNATQ commented on src/shared/Level/models.ts
> +export type LevelRank = IntRange<1, 10>;
J'ai modifié le type `IntRange` pour que l'entièreté de l'intervalle soit comprit

2022-12-26 14:46 UTC, MASBERNATQ commented on src/shared/Level/models.ts
> +export type LevelRank = IntRange<1, 10>;
✅

2022-12-26 14:46 UTC, MASBERNATQ commented on src/shared/Title/models.ts
>  export type TitleType = 'h1' | 'h2' | 'h3' | 'h4' | 'none';
Yep, serait fait dans la refacto également

2022-12-26 14:49 UTC, MASBERNATQ commented on src/shared/_helpers/ArrayHelpers.ts
> +  }
Si c'est un `array` : 
- et qu'il n'y a aucun élément, alors la fonction renverra **true**
- et qu'il y a au moins un élément, alors la fonction renverra **false**

Si ce n'est pas un `array`, la fonction renvoie **true**

2022-12-26 14:50 UTC, MASBERNATQ commented on src/shared/_helpers/ArrayHelpers.ts
> +  }
✅

2022-12-26 14:53 UTC, MASBERNATQ commented on src/shared/_helpers/ArrayHelpers.ts
> +  static isEmpty(value: any): any {
Le type `unknown` ne fonctionnera pas dans ce cas là car on y applique une méthode par la suite `value.length === 0` (_'value' is of type 'unknown'_)

2022-12-26 14:56 UTC, MASBERNATQ commented on src/socket/listeningEvents.ts
> +// FIXME: assign the right type for parameter or just 'any' ?
Je suis totalement d'accord avec toi `any `est à bannir mais comme les données proviennent de l'API on ne sait pas ce qu'elles contiennent puisque c'est en dehors du périmètre du front. Donc je pense à l'heure actuelle garder le `any` mais je vais checker pour trouver une solution alternative à ça quand même. Si je change ce type, ça sera fait dans le ticket de refacto

2022-12-26 14:56 UTC, MASBERNATQ commented on src/socket/listeningEvents.ts
> +export const listeningPlayerJoined = (gameRoomData: any): void => {
Données provenant de l'API, pas de contrôle dessus malheureusement

2022-12-26 14:56 UTC, MASBERNATQ commented on src/socket/listeningEvents.ts
> +export const listeningGameCreated = (gameRoomData: any): void => {
Données provenant de l'API, pas de contrôle dessus malheureusement

2022-12-26 14:57 UTC, MASBERNATQ commented on src/socket/listeningEvents.ts
> +export const listeningGameInformation = (gameRoomData: any): void => {
Données provenant de l'API, pas de contrôle dessus malheureusement

2022-12-26 14:57 UTC, MASBERNATQ commented on src/socket/listeningEvents.ts
> +export const listeningOnePlayerHasPlacedHisBoats = (gameRoomData: any): void => {
Données provenant de l'API, pas de contrôle dessus malheureusement

2022-12-26 14:57 UTC, MASBERNATQ commented on src/weapon/helpers.ts
> +export const parseWeapon = (weapon: any): Weapon => ({
Données provenant de l'API, pas de contrôle dessus malheureusement

2022-12-26 15:00 UTC, MASBERNATQ commented on src/weapon/helpers.ts
> +  maxAmmunition: weapon?.maxAmmunition || 0,
Bien je me dis que si l'API ne renvoie pas la bonne valeur sur une arme spéciale, je préfère assigner une valeur sur 0 afin d'éviter que le joueur puisse utiliser à l'infini cette arme spéciale. Mais si ce n'est pas gênant je peux mettre **-1** pour le coup

2022-12-26 15:00 UTC, MASBERNATQ commented on src/weapon/helpers.ts
> +  ArrayHelpers.isArray(weapons) ? weapons.map((weapon: any) => parseWeapon(weapon)) : [];
Données provenant de l'API, pas de contrôle dessus malheureusement

2022-12-26 18:20 UTC, FlavianEng commented on src/socket/listeningEvents.ts
> +export const listeningGameInformation = (gameRoomData: any): void => {
You can use `unknown` instead

2022-12-26 18:21 UTC, FlavianEng commented on src/socket/listeningEvents.ts
> +export const listeningOnePlayerHasPlacedHisBoats = (gameRoomData: any): void => {
You can use `unknown` instead

2022-12-26 18:21 UTC, FlavianEng commented on src/weapon/helpers.ts
> +export const parseWeapon = (weapon: any): Weapon => ({
You can use `unknown` instead

2022-12-26 18:21 UTC, FlavianEng commented on src/weapon/helpers.ts
> +  maxAmmunition: weapon?.maxAmmunition || 0,
Na na pas gênant de toute, c'est le back qui bloquera

2022-12-26 18:21 UTC, FlavianEng commented on src/weapon/helpers.ts
> +  ArrayHelpers.isArray(weapons) ? weapons.map((weapon: any) => parseWeapon(weapon)) : [];
You can use `unknown` instead

2022-12-26 18:36 UTC, FlavianEng commented on src/boat/helpers.ts
> +export const parseBoat = (boat: any): Boat => ({
Can you use `unknown` instead ?

2022-12-26 18:36 UTC, FlavianEng commented on src/boat/helpers.ts
> +export const parseBoats = (boats: any): Boat[] =>
Can you use `unknown` instead ?

2022-12-26 18:36 UTC, FlavianEng commented on src/boat/helpers.ts
> +  ArrayHelpers.isArray(boats) ? boats.map((boat: any) => parseBoat(boat)) : [];
Can you use `unknown` instead ?

2022-12-26 18:36 UTC, FlavianEng commented on src/boat/helpers.ts
> +export const parseAuthorizedBoat = (authorizedBoat: any): AuthorizedBoat => ({
Can you use `unknown` instead ?

2022-12-26 18:36 UTC, FlavianEng commented on src/boat/helpers.ts
> + * @param {any} authorisedFleet Authorized fleet
Can you use `unknown` instead ?

2022-12-26 18:36 UTC, FlavianEng commented on src/boat/helpers.ts
> +    }
With early return, this part should looks like this (rewrite it in your IDE) 

```suggestion
    if (isBoatHorizontal(boardBoat.direction)) {
    
      if (hasYAxisReversed(boardBoat.direction)) {
        bowCells.push([boardBoat.x, boardBoat.y - index]);
        return;
      } 
      
        bowCells.push([boardBoat.x, boardBoat.y + index]);    
      return;
    } 
    

      if (hasXAxisReversed(boardBoat.direction)) {
        bowCells.push([boardBoat.x - index, boardBoat.y]);
        return;
      } 
      
        bowCells.push([boardBoat.x + index, boardBoat.y]);
      
   
```

2022-12-26 18:36 UTC, FlavianEng commented on src/game/helpers.ts
> +export const parseGamePlayer = (gamePlayer: any): GamePlayer => ({
Same answer

2022-12-26 18:36 UTC, FlavianEng commented on src/game/helpers.ts
> +  hasBoatsSafetyZone: gameSettings?.hasBoatsSafetyZone || GAME_SETTINGS.hasBoatsSafetyZone,
```suggestion
  hasBoatsSafetyZone: gameSettings?.hasBoatsSafetyZone ?? GAME_SETTINGS.hasBoatsSafetyZone,
```

2022-12-26 18:36 UTC, FlavianEng commented on src/home/components/HomePageContent.tsx
> +    dispatch(setGameRoom({} as GameRoom));
ok

2022-12-26 18:36 UTC, FlavianEng commented on src/shared/Board/components/Board.tsx
> +      }
Take example of the suggestion I wrote above

2022-12-26 18:36 UTC, FlavianEng commented on src/shared/_helpers/ArrayHelpers.ts
> +  static isArray(value: any): boolean {
```suggestion
   * @param {unknown} value Value to check
   * @return {boolean}
   */
  static isArray(value: unknown): boolean {
```

2022-12-26 18:36 UTC, FlavianEng commented on src/shared/_helpers/ArrayHelpers.ts
> +  static isEmpty(value: any): boolean {
```suggestion
   * @param {unknown} value Value to check
   * @return {boolean}
   */
  static isEmpty(value: unknown): boolean {
```

2022-12-26 18:36 UTC, FlavianEng commented on src/shared/_helpers/ArrayHelpers.ts
> +  static getRandomItem(array: any[]): any {
```suggestion
   * @param {unknown[]} array Array
   * @return {any}
   */
  static getRandomItem(array: unknown[]): any {
```

2022-12-26 18:36 UTC, FlavianEng commented on src/socket/listeningEvents.ts
> +// FIXME: assign the right type for parameter or just 'any' ?
Le unknown existe pas pour rien !

2022-12-28 16:33 UTC, FlavianEng commented on src/shared/Board/components/Board.tsx
> +          }
```suggestion
          if (!checkBoardBoatsPosition(newBoats, dimensions, hasBoatsSafetyZone)) {
             return false;
          } 
          
          setBoats?.(newBoats);
```

2022-12-29 16:39 UTC, MASBERNATQ commented on src/game/helpers.ts
> +  hasBoatsSafetyZone: gameSettings?.hasBoatsSafetyZone || GAME_SETTINGS.hasBoatsSafetyZone,
✅

2022-12-29 16:41 UTC, MASBERNATQ commented on src/shared/_helpers/ArrayHelpers.ts
> +  static isEmpty(value: any): boolean {
Pas possible de typer en `unknown` car dans la fonction **isEmpty** une méthode est appliqué à **value** :

> value.length

2022-12-29 16:42 UTC, MASBERNATQ commented on src/shared/_helpers/ArrayHelpers.ts
> +  static isEmpty(value: any): boolean {
✅

2022-12-29 16:43 UTC, MASBERNATQ commented on src/shared/_helpers/ArrayHelpers.ts
> +  static isArray(value: any): boolean {
✅

2022-12-29 16:51 UTC, MASBERNATQ commented on src/shared/_helpers/ArrayHelpers.ts
> +  static getRandomItem(array: any[]): any {
✅

2022-12-29 17:03 UTC, MASBERNATQ commented on src/shared/_helpers/ArrayHelpers.ts
> +  static getRandomItem(array: any[]): any {
est-ce que tu penses quelque chose comme ça serait plus propre ?

```js
/**
   * Get a random item in the array.
   *
   * @param {unknown[]} array Array
   * @return {any}
   */
  static getRandomItem<T>(array: T[]): T {
    return array[Math.floor(Math.random() * array.length)];
  }
```

2022-12-29 17:04 UTC, MASBERNATQ commented on src/shared/Board/components/Board.tsx
> +          }
✅

2022-12-29 17:12 UTC, MASBERNATQ commented on src/boat/helpers.ts
> +    }
Je ne peux pas faire des retours en pleins dans ma fonction car je boucle justement pour mettre les positions dans `bowCells` et après je retourne `bowCells`. Là en l'occurrence ça renverrai `undefined` alors qu'on s'attends à un retour de type `ApiPosition[]`

2022-12-29 17:20 UTC, MASBERNATQ commented on src/game/components/GameOneVersusOne/GamePlacingBoatsView.tsx
> +    }
✅

2022-12-29 17:21 UTC, MASBERNATQ commented on src/shared/Board/components/Board.tsx
> +      }
✅

2022-12-29 18:18 UTC, FlavianEng commented on src/boat/helpers.ts
> +    }
C'est sur que tu peux le faire sans else, j'approve quand même

2022-12-29 18:19 UTC, FlavianEng commented on src/shared/_helpers/ArrayHelpers.ts
> +  static getRandomItem(array: any[]): any {
Très largement meilleur ! Faudra juste update la jsDoc pour le generic Type

2022-12-29 18:24 UTC, FlavianEng submitted a review, later dismissed

2022-12-30 08:15 UTC, FlavianEng commented on src/shared/_helpers/ArrayHelpers.ts
> +  static getRandomItem(array: any[]): any {
Tu peux le faire plus tard pour la doc

2022-12-30 10:04 UTC, MASBERNATQ commented on src/shared/_helpers/ArrayHelpers.ts
> +  static getRandomItem(array: any[]): any {
✅

2022-12-30 10:09 UTC, FlavianEng submitted a review, later dismissed

2022-12-30 10:11 UTC, FlavianEng approved these changes

2022-12-30 10:15 UTC, MaximeWrlz approved these changes

2022-12-30 10:17 UTC, merged